### ISSUE TITLE
Error in Running Pre-Trained Model

### ISSUE THREAD

**Issue by Zoher15** [yasumasaonoe/Box4Types#10]
Hi @yasumasa @yasumasaonoe 

I want to use your model for a downstream task. I want to detect figer entities in text. I am trying to figure out how to use your model for that.....

I tried to run using the figer model you attached. But I got the following error:

```
[zkachwal@x1000c0s1b0n1 box4et]$ bash eval_box.sh
seed: 0
TransformerBoxModel
Initializing <bert-large-uncased-whole-word-masking> model...
Some weights of the model checkpoint at bert-large-uncased-whole-word-masking were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Not loading pretrained box emb.
--------------------------------------------------------------------------------
model_id : box_figer_dev
device : cuda
n_gpu : 1
mode : test
local_rank : -1
train_data : 
dev_data : 
eval_data : figer/figer_dev.json
goal : figer
seed : 0
context_window_size : 100
num_epoch : 100
per_gpu_train_batch_size : 8
per_gpu_eval_batch_size : 8
learning_rate_enc : 2e-05
learning_rate_cls : 0.001
adam_epsilon_enc : 1e-08
adam_epsilon_cls : 1e-08
hidden_dropout_prob : 0.0
n_negatives : 0
neg_temp : 0.0
gradient_accumulation_steps : 1
alpha_l2_reg_cls : -1.0
use_scheduler_enc : False
use_scheduler_cls : False
scheduler_type : cyclic
step_size_up : 2000
warmup_steps : 0
max_steps : 1000000
model_type : bert-large-uncased-whole-word-masking
emb_type : box
mc_box_type : CenterSigmoidBoxTensor
type_box_type : CenterSigmoidBoxTensor
box_dim : 109
box_offset : 0.5
threshold : 0.5
alpha_type_reg : 0.0
th_type_vol : 0.0
alpha_type_vol_l1 : 0.0
alpha_type_vol_l2 : 0.0
marginal_scale : 1.0
avg_pooling : False
inv_softplus_temp : 1.2471085395024732
softplus_scale : 1.0
proj_layer : highway
n_proj_layer : 2
use_gumbel_baysian : False
gumbel_beta : 0.00036026463511690845
reduced_type_emb_dim : -1
alpha_hierarchy_loss : 0.0
conditional_prob_path : 
marginal_prob_path : 
encoder_layer_ids : None
save_period : 1000
save_best_model : True
eval_period : 500
log_period : 1000
eval_after : 10
max_num_eval : -1
load : True
reload_model_name : box_figer
pretrained_box_path : 
use_wandb : False
wandb_project_name : 
wandb_username : 
do_lower : True
max_position_embeddings : 512
--------------------------------------------------------------------------------
==> mode: test
==> Start eval...
==> Loading data generator... 
Found 1 shards at ../data/figer/figer_dev.json
==> Loading ID -> TYPE mapping... 
Traceback (most recent call last):
  File "main.py", line 993, in <module>
    main()
  File "main.py", line 987, in main
    _test(args, model, device)
  File "main.py", line 894, in _test
    args.model_id, model)
  File "main.py", line 492, in load_model
    model.load_state_dict(checkpoint["state_dict"])
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerBoxModel:
        Missing key(s) in state_dict: "encoder.embeddings.position_ids". 
```

Thanks for your time!

Best,
Zoher

**Comment by Zoher15** [comment]
I was able to get around this, by training a model using your framework....
